In [1]:
import numpy
numpy.__version__

'1.15.1'

In [1]:
import numpy as np

In [3]:
np.__version__

'1.15.1'

In [7]:
#создание np.array из списка
a = np.array([1, 4, 2, 5, 3])

In [9]:
a

array([1, 4, 2, 5, 3])

In [10]:
# приводение к одному типу

In [14]:
np.array([3.14, 1])

array([3.14, 1.  ])

In [31]:
np.array([True, 1])

array([1, 1])

In [32]:
np.array([True, 2, False])

array([1, 2, 0])

In [35]:
np.array([True, bool(1), False])

array([ True,  True, False])

In [36]:
np.array([True, 2, False], dtype='bool')

array([ True,  True, False])

In [39]:
np.array([True, 2, False], dtype=bool)

array([ True,  True, False])

In [38]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [5]:
np.zeros?

In [6]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [9]:
np.linspace(0,1,7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [10]:
np.random.random((3,3))

array([[0.75614051, 0.11553781, 0.19037486],
       [0.29909947, 0.4144822 , 0.54111477],
       [0.13459942, 0.33698494, 0.92948897]])

In [11]:
np.random.normal(0,1,(3,3))

array([[ 0.66227143, -0.87908124, -0.37333425],
       [-0.0618051 , -1.37270013, -0.21425051],
       [-1.08239501,  2.09408613,  1.77930059]])

In [17]:
np.random.randint(0, 10, (3,3))

array([[0, 0, 0],
       [1, 8, 5],
       [7, 3, 2]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.empty(3)

array([1., 1., 1.])

In [15]:
np.empty?

In [18]:
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])